
version: "3"
services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - ./qbt/config:/config
      - ./qbt/downloads:/downloads
      - ./qbt/watch:/watch
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    ports:
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - pt


  flexget:
    restart: unless-stopped
#    image: kmb32123/flexget-dockerfile:alpine-python3 # for amd64
    image: pejter/flexget:alpine # for amd64/arm64
    container_name: flexget
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./flexget:/flexget
      - ./qbt/watch:/qbt/watch
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    networks:
      - pt

  nginx:
    restart: always
    image: nginx:mainline
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/well-known:/var/www/html/well-known
      - ./nginx/acme.sh:/etc/ssl/letsencrypt
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    networks:
      - pt

  acme-sh:
    image: neilpang/acme.sh
    container_name: acme-sh
    volumes:
      - ./nginx/acme.sh:/acme.sh
    command: daemon
    networks:
      - pt

  # emby:
  #   restart: always
  #   image: emby/embyserver:latest
  #   container_name: emby
  #   volumes:
  #     - ./emby/config:/config
  #     - ./qbt/downloads:/mnt
  #   environment:
  #     - UID=2
  #     - GID=44
  #     - GIDLIST=1000
  #   devices:
  #     - /dev/dri/renderD128:/dev/dri/renderD128
  #   networks:
  #     - pt

  # jellyfin:
  #   restart: always
  #   image: linuxserver/jellyfin:latest
  #   container_name: jellyfin
  #   volumes:
  #     - ./jellyfin/config:/config
  #     - ./jellyfin/transcode:/transcode
  #     - ./qbt/downloads:/data
  #   environment:
  #     - UID=2
  #     - GID=44
  #     - GIDLIST=1000
  #   devices:
  #     - /dev/dri/renderD128:/dev/dri/renderD128
  #   networks:
  #     - pt
networks:
  pt:
   driver: bridge